#!/usr/bin/env bash
# train_lora.sh - Launch SDXL LoRA training with kohya sd-scripts.
#
#   source ~/sd-venv/bin/activate
#   bash train/train_lora.sh              # pilot (default)
#   MODE=full bash train/train_lora.sh    # full run
#
# Expects: setup_lambda.sh + pull_data.sh have already run.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
WORKDIR="${WORKDIR:-$HOME}"
SDSCRIPTS_DIR="${SDSCRIPTS_DIR:-$WORKDIR/sd-scripts}"
MODEL="/home/ubuntu/models/sd_xl_base_1.0_fixvae_fp16.safetensors"

# --- GPU count + per-GPU batch size -----------------------------------------
# Defaults target 1× A100 40GB (stable, no multi-GPU fabric headaches).
# BATCH_SIZE is per-GPU and must match train_batch_size in config_*.toml.
# Effective batch = BATCH_SIZE × GRAD_ACCUM_STEPS (not × NUM_GPUS).
# Override NUM_GPUS only if you deliberately want multi-GPU DDP.
NUM_GPUS="${NUM_GPUS:-1}"
BATCH_SIZE="${BATCH_SIZE:-4}"
GRAD_ACCUM_STEPS="${GRAD_ACCUM_STEPS:-4}"

MODE="${MODE:-pilot}"
if [ "$MODE" = "pilot" ]; then
    TRAIN_DATA="${TRAIN_DATA:-/home/ubuntu/train_data_pilot}"
    CONFIG="${CONFIG:-$REPO_DIR/train/config_pilot.toml}"
elif [ "$MODE" = "full" ]; then
    TRAIN_DATA="${TRAIN_DATA:-/home/ubuntu/train_data}"
    CONFIG="${CONFIG:-$REPO_DIR/train/config.toml}"
else
    echo "ERROR: MODE must be 'pilot' or 'full' (got '$MODE')" >&2
    exit 1
fi

# dataset.toml is generated here so image_dir is always correct for this MODE.
DATASET_CONFIG="/home/ubuntu/dataset_${MODE}.toml"

mkdir -p /home/ubuntu/models /home/ubuntu/out /home/ubuntu/logs

# kohya reads sample_prompts from an absolute path in config_*.toml
cp "$REPO_DIR/train/sample_prompts.txt" /home/ubuntu/sample_prompts.txt

# --- Generate dataset.toml pointing at the correct image_dir ----------------
echo "==> Writing $DATASET_CONFIG (image_dir=$TRAIN_DATA)"
cat > "$DATASET_CONFIG" <<TOML
# kohya sd-scripts dataset config (DreamBooth-style, .txt caption sidecars)
# Auto-generated by train_lora.sh for MODE=$MODE.
[general]
caption_extension = ".txt"
shuffle_caption = true
keep_tokens = 1
enable_bucket = true
bucket_no_upscale = true

[[datasets]]
resolution = [1024, 1024]
batch_size = $BATCH_SIZE
min_bucket_reso = 512
max_bucket_reso = 2048

  [[datasets.subsets]]
  image_dir = "$TRAIN_DATA"
  num_repeats = 1
  cache_info = true
TOML

# --- Download SDXL base (fixed-VAE fp16) if missing -------------------------
if [ ! -f "$MODEL" ]; then
    echo "==> Downloading SDXL base model (fixed-VAE fp16)"
    python - <<'PY'
from huggingface_hub import hf_hub_download
import shutil, os
p = hf_hub_download(
    repo_id="bdsqlsz/stable-diffusion-xl-base-1.0_fixvae_fp16",
    filename="sd_xl_base_1.0_fixvae_fp16.safetensors",
)
os.makedirs("/home/ubuntu/models", exist_ok=True)
shutil.copy(p, "/home/ubuntu/models/sd_xl_base_1.0_fixvae_fp16.safetensors")
print("downloaded base model")
PY
fi

[ -f "$CONFIG" ] || { echo "ERROR: train config not found: $CONFIG" >&2; exit 1; }
[ -d "$TRAIN_DATA" ] || { echo "ERROR: TRAIN_DATA not found: $TRAIN_DATA — run pull_data.sh first" >&2; exit 1; }

if [ "$NUM_GPUS" -gt 1 ]; then
    echo "WARNING: NUM_GPUS=$NUM_GPUS — multi-GPU DDP enabled. Project defaults to 1× A100." >&2
fi

# --- Optional fast bad-image scan (parallel, no deletes) ----------------------
if [ "${CHECK_IMAGES:-1}" = "1" ]; then
    echo "==> Checking images in $TRAIN_DATA (parallel scan, no deletes)"
    python "$REPO_DIR/train/check_images.py" "$TRAIN_DATA" \
        --max-long-side "${MAX_LONG_SIDE:-2048}" \
        --workers "${CHECK_WORKERS:-$(nproc)}" || true
fi

# --- Prune corrupt / oversized images (idempotent; fast when data is clean) -
# Set PRUNE_IMAGES=0 to skip when data was validated locally before packaging.
MAX_LONG_SIDE="${MAX_LONG_SIDE:-2048}"
if [ "${PRUNE_IMAGES:-1}" = "1" ]; then
    echo "==> Pruning bad images in $TRAIN_DATA (max long side ${MAX_LONG_SIDE}px)"
    python "$REPO_DIR/train/prune_bad_images.py" "$TRAIN_DATA" --max-long-side "$MAX_LONG_SIDE"
else
    echo "==> Skipping prune (PRUNE_IMAGES=0)"
fi

if [ "${CHECK_IMAGES:-1}" = "1" ]; then
    echo "==> Verifying image dir is clean before training"
    python "$REPO_DIR/train/check_images.py" "$TRAIN_DATA" \
        --max-long-side "$MAX_LONG_SIDE" \
        --workers "${CHECK_WORKERS:-$(nproc)}" \
        --fail
fi

# --- Fail-fast: never silently train on CPU --------------------------------
# accelerate will quietly fall back to CPU if the NVIDIA driver is missing,
# turning a ~1-2h run into days. Abort loudly instead.
python - <<'PY'
import sys, torch
if not torch.cuda.is_available():
    sys.exit("FATAL: torch.cuda.is_available() is False — refusing to launch on CPU. "
             "Run nvidia-smi; if it fails, (re)install the driver (see setup_lambda.sh).")
print(f"CUDA OK: {torch.cuda.get_device_name(0)}")
PY

cd "$SDSCRIPTS_DIR"
echo "==> Launching SDXL LoRA training (MODE=$MODE)"
echo "    train config:    $CONFIG"
echo "    dataset config:  $DATASET_CONFIG"
echo "    image_dir:       $TRAIN_DATA"
echo "    GPUs:            $NUM_GPUS"
echo "    per-GPU batch:   $BATCH_SIZE"
echo "    grad accum:      $GRAD_ACCUM_STEPS  (effective batch = $((BATCH_SIZE * GRAD_ACCUM_STEPS * NUM_GPUS)))"

# --num_processes is passed explicitly so the launch is correct even if the
# cached accelerate default_config.yaml is stale. With NUM_GPUS>1 this runs DDP.
accelerate launch --num_processes "$NUM_GPUS" --num_cpu_threads_per_process 8 \
    sdxl_train_network.py \
    --config_file "$CONFIG" \
    --dataset_config "$DATASET_CONFIG"

echo "==> Training finished. LoRA written under /home/ubuntu/out"
echo "    Push it to R2 with: MODE=$MODE bash train/push_model.sh"
