#!/usr/bin/env bash
# train_lora.sh - Launch SDXL LoRA training with kohya sd-scripts.
#
#   source ~/sd-venv/bin/activate
#   bash train/train_lora.sh              # pilot (default)
#   MODE=full bash train/train_lora.sh    # full run
#
# Expects: setup_lambda.sh + pull_data.sh have already run.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
WORKDIR="${WORKDIR:-$HOME}"
SDSCRIPTS_DIR="${SDSCRIPTS_DIR:-$WORKDIR/sd-scripts}"
MODEL="/home/ubuntu/models/sd_xl_base_1.0_fixvae_fp16.safetensors"

# --- GPU count + per-GPU batch size -----------------------------------------
# NUM_GPUS drives accelerate --num_processes (DDP across GPUs). BATCH_SIZE is the
# PER-GPU batch and must match train_batch_size in the chosen config_*.toml.
# Effective batch = BATCH_SIZE * NUM_GPUS. Defaults tuned for 2× H100 80GB
# (per-GPU 8 → effective 16). Override either via env if your box differs.
NUM_GPUS="${NUM_GPUS:-$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | wc -l)}"
[ "$NUM_GPUS" -ge 1 ] 2>/dev/null || NUM_GPUS=1
BATCH_SIZE="${BATCH_SIZE:-8}"

MODE="${MODE:-pilot}"
if [ "$MODE" = "pilot" ]; then
    TRAIN_DATA="${TRAIN_DATA:-/home/ubuntu/train_data_pilot}"
    CONFIG="${CONFIG:-$REPO_DIR/train/config_pilot.toml}"
elif [ "$MODE" = "full" ]; then
    TRAIN_DATA="${TRAIN_DATA:-/home/ubuntu/train_data}"
    CONFIG="${CONFIG:-$REPO_DIR/train/config.toml}"
else
    echo "ERROR: MODE must be 'pilot' or 'full' (got '$MODE')" >&2
    exit 1
fi

# dataset.toml is generated here so image_dir is always correct for this MODE.
DATASET_CONFIG="/home/ubuntu/dataset_${MODE}.toml"

mkdir -p /home/ubuntu/models /home/ubuntu/out /home/ubuntu/logs

# --- Generate dataset.toml pointing at the correct image_dir ----------------
echo "==> Writing $DATASET_CONFIG (image_dir=$TRAIN_DATA)"
cat > "$DATASET_CONFIG" <<TOML
# kohya sd-scripts dataset config (DreamBooth-style, .txt caption sidecars)
# Auto-generated by train_lora.sh for MODE=$MODE.
[general]
caption_extension = ".txt"
shuffle_caption = true
keep_tokens = 1
enable_bucket = true
bucket_no_upscale = true

[[datasets]]
resolution = [1024, 1024]
batch_size = $BATCH_SIZE
min_bucket_reso = 512
max_bucket_reso = 2048

  [[datasets.subsets]]
  image_dir = "$TRAIN_DATA"
  num_repeats = 1
  cache_info = true
TOML

# --- Download SDXL base (fixed-VAE fp16) if missing -------------------------
if [ ! -f "$MODEL" ]; then
    echo "==> Downloading SDXL base model (fixed-VAE fp16)"
    python - <<'PY'
from huggingface_hub import hf_hub_download
import shutil, os
p = hf_hub_download(
    repo_id="bdsqlsz/stable-diffusion-xl-base-1.0_fixvae_fp16",
    filename="sd_xl_base_1.0_fixvae_fp16.safetensors",
)
os.makedirs("/home/ubuntu/models", exist_ok=True)
shutil.copy(p, "/home/ubuntu/models/sd_xl_base_1.0_fixvae_fp16.safetensors")
print("downloaded base model")
PY
fi

[ -f "$CONFIG" ] || { echo "ERROR: train config not found: $CONFIG" >&2; exit 1; }
[ -d "$TRAIN_DATA" ] || { echo "ERROR: TRAIN_DATA not found: $TRAIN_DATA — run pull_data.sh first" >&2; exit 1; }

if [ "$NUM_GPUS" -eq 1 ]; then
    echo "WARNING: 1 GPU detected — configs assume 2× H100 (effective batch 16)." >&2
    echo "         Expect ~4-6× longer latent caching + training vs 2× H100." >&2
fi

# --- Prune corrupt / oversized images (idempotent; fast when data is clean) -
MAX_LONG_SIDE="${MAX_LONG_SIDE:-2048}"
echo "==> Pruning bad images in $TRAIN_DATA (max long side ${MAX_LONG_SIDE}px)"
python "$REPO_DIR/train/prune_bad_images.py" "$TRAIN_DATA" --max-long-side "$MAX_LONG_SIDE"

# --- Fail-fast: never silently train on CPU --------------------------------
# accelerate will quietly fall back to CPU if the NVIDIA driver is missing,
# turning a ~1-2h run into days. Abort loudly instead.
python - <<'PY'
import sys, torch
if not torch.cuda.is_available():
    sys.exit("FATAL: torch.cuda.is_available() is False — refusing to launch on CPU. "
             "Run nvidia-smi; if it fails, (re)install the driver (see setup_lambda.sh).")
print(f"CUDA OK: {torch.cuda.get_device_name(0)}")
PY

cd "$SDSCRIPTS_DIR"
echo "==> Launching SDXL LoRA training (MODE=$MODE)"
echo "    train config:    $CONFIG"
echo "    dataset config:  $DATASET_CONFIG"
echo "    image_dir:       $TRAIN_DATA"
echo "    GPUs:            $NUM_GPUS"
echo "    per-GPU batch:   $BATCH_SIZE  (effective batch = $((BATCH_SIZE * NUM_GPUS)))"

# --num_processes is passed explicitly so the launch is correct even if the
# cached accelerate default_config.yaml is stale. With NUM_GPUS>1 this runs DDP.
accelerate launch --num_processes "$NUM_GPUS" --num_cpu_threads_per_process 8 \
    sdxl_train_network.py \
    --config_file "$CONFIG" \
    --dataset_config "$DATASET_CONFIG"

echo "==> Training finished. LoRA written under /home/ubuntu/out"
echo "    Push it to R2 with: MODE=$MODE bash train/push_model.sh"
